# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildCOnfiguration: 'Release'
  webRepository: 'possellapi'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'secret'
stages:
- stage: 'BuildTest'
  displayName: 'Compila y prueba'
  jobs: 
  - job: 'BuildAndTest'
    displayName: 'job que compila y prueba'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '$(solution)'     
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        
